import { SelectStyledFooterProps, SelectStyledInputProps, SelectStyledListProps, SelectStyledOptionProps, SelectWrapperProps } from '.';

export declare const SelectWrapper: import('styled-components/dist/types').IStyledComponentBase<"web", import('styled-components/dist/types').Substitute<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, SelectWrapperProps>> & string;
export declare const DropdownListParent: import('styled-components/dist/types').IStyledComponentBase<"web", import('styled-components/dist/types').Substitute<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, SelectStyledListProps>> & string;
export declare const DropdownList: import('styled-components/dist/types').IStyledComponentBase<"web", import('styled-components').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLUListElement>, HTMLUListElement>, never>> & string;
export declare const DropdownOption: import('styled-components/dist/types').IStyledComponentBase<"web", import('styled-components/dist/types').Substitute<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').LiHTMLAttributes<HTMLLIElement>, HTMLLIElement>, SelectStyledOptionProps>> & string;
export declare const DropdownFooter: import('styled-components/dist/types').IStyledComponentBase<"web", import('styled-components/dist/types').Substitute<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').LiHTMLAttributes<HTMLLIElement>, HTMLLIElement>, SelectStyledFooterProps>> & string;
export declare const DropdownErase: import('styled-components/dist/types').IStyledComponentBase<"web", import('styled-components').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>> & string;
export declare const DropdownSelectAll: import('styled-components/dist/types').IStyledComponentBase<"web", import('styled-components').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>> & string;
export declare const SelectStyledInput: import('styled-components/dist/types').IStyledComponentBase<"web", import('styled-components/dist/types').Substitute<Omit<import('styled-components').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>, keyof import('../input').StyledInputProps> & import('../input').StyledInputProps, "ref"> & {
    ref?: ((instance: HTMLInputElement | null) => void) | import('../../../node_modules/react').RefObject<HTMLInputElement> | null | undefined;
}, SelectStyledInputProps>> & string;
